---
- hosts: all
  gather_facts: false
  vars_files:
    - vars.yml

  vars:
    ansible_python_interpreter: "/usr/bin/python3"

  tasks:
  - include_tasks: "tasks/ad_step1.yml"

- hosts: "ad"
  gather_facts: false
  vars_files:
    - vars.yml

  vars:
    ansible_python_interpreter: "/usr/bin/python3"

  tasks:
  - include_tasks: "tasks/ad_step2.yml"
