---
- hosts: all
  gather_facts: false
  vars_files:
    - vars.yml

  vars:
    ansible_python_interpreter: "/usr/bin/python3"

  tasks:

  - name: Add localhost
    add_host:
      name: localhost
      connection: local
      ansible_connection: local

  - name: Base | Installing knowsmore python lib
    ansible.builtin.pip:
      name:
        - knowsmore
    delegate_to: localhost

  - name: Add new PDC to Ansible Hosts
    add_host:
      name: '{{ dc_address }}'
      ansible_connection: winrm
      ansible_winrm_transport: ntlm
      ansible_winrm_server_cert_validation: ignore
      ansible_winrm_port: 5986
      group: "ad"

- hosts: "ad"
  gather_facts: false
  vars_files:
    - vars.yml

  vars:
    ansible_python_interpreter: "/usr/bin/python3"
    dc_creds: &dc_creds
      domain_password: '{{ ansible_password }}'
      domain_username: '{{ ansible_user }}'
      domain_server: '{{ dc_address }}'

  tasks:
  - name: Wait for system to become reachable over new ip
    wait_for_connection:
      timeout: 900

  - name: Ensure a server is a domain controller
    ansible.windows.win_domain_controller:
      dns_domain_name: '{{ domain_name }}'
      domain_admin_user: '{{ ansible_user + "@" + domain_name }}'
      domain_admin_password: '{{ ansible_password }}'
      safe_mode_password: '{{ ansible_password }}'
      state: domain_controller
    register: ad_data

  - name: Get default OU 'computers'
    community.windows.win_domain_ou:
      <<: *dc_creds
      name: 'computers'
      state: present
    register: computers_ou
    ignore_errors: true
    retries: 5
    delay: 10
    until: computers_ou['path'] is defined and computers_ou['path'][0] is defined and computers_ou['path'][0] != ''

  - name: Get root DN
    set_fact:
      root_dn: "{{ computers_ou['path'][0] | string }}"

  - debug: msg="{{ root_dn }}"

  - name: Create object structure
    generate_ad_data:
      user: 5000
      group: 200
      ou: 30
      domain_admins: 50
      spn: 70
      company_name: '{{ company_name }}'
      base_dn: '{{ root_dn }}'
    connection: local
    register: ad_new_objects
    delegate_to: localhost

  - name: Create OUs
    populate_ad:
      <<: *dc_creds
      ous: "{{ ad_new_objects['ous'] | list }}"

  - name: Create groups
    populate_ad:
      <<: *dc_creds
      groups: "{{ ad_new_objects['groups'] | list }}"

  - name: Create users
    populate_ad:
      <<: *dc_creds
      users: "{{ ad_new_objects['users'] | list }}"
