---
- hosts: all
  gather_facts: false
  vars_files:
    - vars.yml

  vars:
    ansible_python_interpreter: "/usr/bin/python3"
    #ansible_connection: winrm
    #ansible_winrm_transport: ntlm
    #ansible_winrm_server_cert_validation: ignore
    #ansible_winrm_port: 5986

  tasks:

  - name: Add new PDC to Ansible Hosts
    add_host:
      name: '{{ dc_address }}'
      ansible_connection: winrm
      ansible_winrm_transport: ntlm
      ansible_winrm_server_cert_validation: ignore
      ansible_winrm_port: 5986
      domain_password: '{{ ansible_password }}'
      domain_username: '{{ ansible_user }}'
      domain_server: '{{ dc_address }}'
      group: "ad"
      
- hosts: "ad"
  gather_facts: true
  vars_files:
    - vars.yml

  vars:
    ansible_python_interpreter: "/usr/bin/python3"

    reverse_dns_zone: "{{ ((dc_address|string) + '/' + (dc_netmask_cidr|string)) | ansible.utils.ipaddr('network/prefix') }}"

  tasks:

  - name: Set the maximum password age
    community.windows.win_security_policy:
      section: System Access
      key: MaximumPasswordAge
      value: 365

  - name: Set the minimum password length
    community.windows.win_security_policy:
      section: System Access
      key: MinimumPasswordLength
      value: 4

  - name: Set the password complexity
    community.windows.win_security_policy:
      section: System Access
      key: PasswordComplexity
      value: 0

  - name: Create object structure
    populate_ad:
      user: 5000
      group: 300
      ou: 200
      domain_admins: 20
      spn: 50
      company_name: '{{ company_name }}'
    connection: local
    register: ad_new_objects
    delegate_to: local_action

  - name: Ensure OU is groups
    community.windows.win_domain_ou:
      name: 'groups'
      state: present
    register: groups_ou

  - name: Get root DN
    set_fact:
      root_dn: "{{ groups_ou['path'] }}"

  - name: Get OU groups DN
    set_fact:
      groups_dn: "{{ groups_ou['ou']['DistinguishedName'] }}"

  - name: Ensure OU
    community.windows.win_domain_ou:
      name: 'OUs'
      state: present
    register: base_ou

  - name: Get OU base DN
    set_fact:
      ou_base_dn: "{{ base_ou['ou']['DistinguishedName'] }}"

  - name: Create/update all OUs
    community.windows.win_domain_ou:
      name: '{{ item }}'
      path: '{{ ou_base_dn }}'
      state: present
    loop: "{{ ad_new_objects['data']['ou'] | list }}"

  - name: Create/update all groups
    community.windows.win_domain_group:
      scope: global
      name: '{{ item }}'
      path: '{{ groups_dn }}'
      state: present
    loop: "{{ ad_new_objects['data']['group'] | list }}"

  - name: Create Users
    community.windows.win_domain_user:
      name: '{{ item.name }}'
      password: '{{ item.passwd }}'
      state: present
      path: '{{ "OU=" + item.ou + "," + ou_base_dn }}'
      groups: '{{ item.member_of | list }}'
      password_never_expires: true
    loop: "{{ ad_new_objects['data']['user'] | list }}"


  - name: Update Users SPN
    community.windows.win_domain_user:
      name: '{{ item.name }}'
      spn: '{{ item.spn }}'
    loop: "{{ ad_new_objects['data']['spn'] | list }}"



